### ISSUE TITLE
Removing translation resource from Transifex

### ISSUE THREAD

**Issue by rakekniven** [daita/mood#10]
The app looks deprecated.
So I would like to remove the resource from Transifex.

If you ask why? See https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312

Existing translations are not lost. They will remain in this repository.

@MorrisJobke @rullzer Are there any objections on your part?

btw. No action needed from your side. My rights at Transifex are sufficient to do this.

**Comment by rakekniven** [comment]
Hello @daita , are there any objections on your part?

**Comment by MorrisJobke** [comment]
> btw. No action needed from your side. My rights at Transifex are sufficient to do this.

There is still the transifex bot. So you need to also provide a PR to https://github.com/nextcloud/docker-ci/blob/master/translations/config.json - once it is merged it will be fine to remove the resources. Problem is still, that getting the translations back to transifex if it is really needed is hard, because we have our own format and would need to convert from this back to the `.po` files, which needs to be done to have nothing lost.

**Comment by rakekniven** [comment]
Hello @MorrisJobke ,
understood your message.

Main page of this repo states:
> Note: mood is deprecated and replaced with the Social app in Nextcloud 15

If we do not cleanup Transifex a little we waste translator power and keep old content.

For sure I can provide PR, now I know the way to do that.

**Comment by MorrisJobke** [comment]
> If we do not cleanup Transifex a little we waste translator power and keep old content.
> 
> For sure I can provide PR, now I know the way to do that.

Ah ... yes then we can just drop it. If needed we can get it up again, but it will most likely also have different strings.
